name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  project-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Setup DVC
      run: |
        pip install dvc
    
    - name: Pull DVC cache (optional)
      run: |
        dvc pull -v || echo "No cache to pull"
    
    - name: Check DVC status
      run: |
        dvc status -v || echo "No changes in the DVC pipeline"
    
    - name: Run DVC pipeline
      run: |
        dvc repro -v || echo "No changes to reproduce"
    
    - name: DVC metrics
      run: |
        dvc metrics show || echo "No metrics found"
