name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  project-test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: setup DVC
      run: |
        pip install dvc
    
    - name: run DVC pipeline
      run: |
        dvc repro  